"""Added timestamp column to game state

Revision ID: 407687bafc4d
Revises: 
Create Date: 2023-11-22 17:56:15.297314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407687bafc4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
