"""Added simulation_id to GameStateModel

Revision ID: 46f4d8ee2a8d
Revises: 407687bafc4d
Create Date: 2023-11-22 19:34:52.267798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f4d8ee2a8d'
down_revision = '407687bafc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simulation_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.drop_column('simulation_id')

    # ### end Alembic commands ###
